Revert "cpupower Makefile change to help run the tool without 'make install'"
This reverts commit 5c1de006e8e66b0be05be422416629e344c71652.

While the original commit makes it easier to run cpupower from the local build
directory, it also leaves the binary with a rather poor rpath of './' in it
after it is installed on a system via 'make install'.

This is considered bad practice and can cause cpupower to fail in rpmbuild
with the following error:

ERROR   0004: file '/usr/bin/cpupower' contains an insecure rpath './' in [./]
error: Bad exit status from /var/tmp/rpm-tmp.A6u26r (%install)
    Bad exit status from /var/tmp/rpm-tmp.A6u26r (%install)

Developers should be able to use LD_LIBRARY_PATH to achieve the same effect
and not introduce rpath into the binary.

Signed-off-by: Josh Boyer <jwboyer@feoraproject.org>